server:
  port: 5300
eureka:
  client:
    serviceUrl:
       # this will tell the address of Eureka server
      defaultZone: http://localhost:1111/eureka/
  # the value specified in the appname, with this name it get registered with Eureka server
  instance:
    appname: apigateway
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: ordermodule
        uri: "lb://ORDERSERVICELOADBALANCER/orders"
        predicates:
        - "Path=/orders/**"
      - id: productmodule
        uri: "http://localhost:6500/products"
        predicates:
        - "Path=/products/**"
      - id: usermodule
        uri: "http://localhost:5500/users"
        predicates:
        - "Path=/users/**"