server:
  port: 8500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # this is the address of Eureka server
  instance:
    appname: paymentservice

spring:
  activemq:
    broker-url: tcp://localhost:61616
  application:
    name: paymentservice
  datasource:
    url: jdbc:mysql://localhost:3306/ordermgmtdb
    username: root
    password: secret
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10